name: Backstageify

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  catalog:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Backstageify
        run: python3 backstageify.py

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Update Backstage catalog-info.yaml"
          git push
